version: "3.8"

services:
  mysql:
    image: 'mysql:8.0.43'
    container_name: 'mysql-container'
    environment:
      - 'MYSQL_ALLOW_EMPTY_PASSWORD=yes'
      - 'MYSQL_DATABASE=eventty_nextgen'
    ports:
      - "3306:3306"