spring:
  config:
    activate:
      on-profile: local

  # Docker 컨테이너로 MySQL, Redis 서버 구동
  docker:
    compose:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
