spring:
  config:
    activate:
      on-profile: test

  docker:
    compose:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
