spring:
  application:
    name: eventty-nextgen
  profiles:
    active: local
  datasource:
    url: ${url}
    username: ${username}
    password: ${password}
    driver-class-name: ${driver-class-name}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

