spring:
  application:
    name: eventty-nextgen
  profiles:
    default: local
    group:
      dev:
        - tomcat
        - metrics
        - properties
        - certification
        - certification-secret
      local:
        - tomcat
        - metrics
        - properties
        - certification
        - certification-secret
      test:
        - tomcat
        - metrics
        - properties
        - certification-test
        - certification-secret-test
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  config:
    import: optional:.env[.properties]
  cloud:
    gcp:
      storage:
        credentials:
          encoded-key: ${GCP_SA_STORAGE_KEY}
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB
      file-size-threshold: 25MB
      location: /tmp/uploads