spring:
  application:
    name: eventty-nextgen
  profiles:
    default: local, properties, metrics
    group:
      dev:
        - certification
        - certification-secret
      local:
        - certification
        - certification-secret
      test:
        - certification-test
        - certification-secret-test
#  data:
#    redis:
#      client-type: lettuce
#      port: 6379
#      host: 127.0.0.1
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  config:
    import: optional:.env[.properties]
  cloud:
    gcp:
      storage:
        credentials:
          encoded-key: ${GCP_SA_IMAGE_KEY}

