url: jdbc:mysql://localhost:3306/eventty_nextgen_test?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
username: jeongbeom4693
password: '00001234'
driver-class-name: com.mysql.cj.jdbc.Driver