certification:
  infoMap:
    client-app0:
      api-permissions:
        user: OPTIONAL
        events: OPTIONAL

        auth_code: FREE
        auth_login: FREE
        auth: LOGIN
    client-app1:
      api-permissions:
        events: OPTIONAL
