spring:
  application:
    name: eventty-nextgen
  profiles:
    default: local
    group:
      dev:
        - properties
        - certification
        - certification-secret
      local:
        - properties
        - certification
        - certification-secret
      test:
        - properties
        - certification-test
        - certification-secret-test
  data:
    redis:
      client-type: lettuce
      port: 6379
      host: 127.0.0.1
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  config:
    import: optional:.env