spring:
  application:
    name: eventty-nextgen
  profiles:
    default: local
    group:
      local:
        - local
        - properties
        - key
      test:
        - test
        - properties
        - key

  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    driver-class-name: ${db.driver-class-name}
  data:
    redis:
      client-type: lettuce
      port: 6379
      host: ${redis.host}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

mail:
  username: ${mail.username}
  password: ${mail.password}




