mail:
  host: smtp.gmail.com
  port: 587
  username: ${mail.username}
  password: ${mail.password}
  default-encoding: UTF-8
  properties:
    timeout: 5000 # 5초
    starttls.enable: true
    auth: true
    debug: true
