authorization:
  infoMap:
    swagger:
      app-permissions:
        all: FREE
    client-app1:
      app-permissions:
        user: OPTIONAL
        certification: OPTIONAL
        events: OPTIONAL
